### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Yusadolat** [Yusadolat/DicoBot#5]
Improve the README file

**Comment by rbo13** [comment]
Can I take this one? Or someone is already working? @Yusadolat

**Comment by Yusadolat** [comment]
No one is working on it.
Please go on :+1:

**Comment by rbo13** [comment]
Hi @Yusadolat, added the enhancements here: https://github.com/Yusadolat/DicoBot/pull/7 you can check it 👍

**Comment by cziem** [comment]
Shouldn't there be a link to the API domains you are using? @Yusadolat
