### ISSUE TITLE
Update Contribution Guide

### ISSUE THREAD

**Issue by Yusadolat** [Yusadolat/DicoBot#6]
Please help Upate User Contribution Guide

**Comment by Variable2016** [comment]
#8 
@Yusadolat  I just sent a PR
Could you please check if it worth merging?

**Comment by Yusadolat** [comment]
@Variable2016 
Thanks so much.
Would check and revert :+1:

**Comment by cziem** [comment]
Are you still in need of enhancing the Contributing file?

**Comment by Yusadolat** [comment]
No 

thanks @phavor
